POST qkdsim.com/getTopology HTTP/1.1
Content-Type: application/json

{"directed": false, "multigraph": false, "graph": [], "nodes": [{"id": "a"}, {"id": "b"}, {"id": "c"}, {"id": "d"}], "adjacency": [[{"id": "b"}, {"id": "c"}, {"id": "d"}], [{"id": "a"}, {"id": "d"}], [{"id": "a"}, {"id": "d"}], [{"id": "a"}, {"id": "b"}, {"id": "c"}]]}

###

POST qkdsim.com/distributeKeys HTTP/1.1

###

POST  qkdsim.com/startSimulation HTTP/1.1
Content-Type: application/json

{"protocol": "bb84", "key_length": 30000, "chunk_size": 5, "chsh_threshold": -2.7, "authentication": "sphincs", "com_channel": "cc1-3", "interceptAndResend": 0, "manInTheMiddle": 0, "source": "endpoint-3", "destination": "endpoint-1"}