
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - qkdsim.s276624.qkdsim.dev
  resources:
  - nettopologys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - qkdsim.s276624.qkdsim.dev
  resources:
  - nettopologys/finalizers
  verbs:
  - update
- apiGroups:
  - qkdsim.s276624.qkdsim.dev
  resources:
  - nettopologys/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - qkdsim.s276624.qkdsim.dev
  resources:
  - qkdsimulators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - qkdsim.s276624.qkdsim.dev
  resources:
  - qkdsimulators/finalizers
  verbs:
  - update
- apiGroups:
  - qkdsim.s276624.qkdsim.dev
  resources:
  - qkdsimulators/status
  verbs:
  - get
  - patch
  - update
